### ISSUE TITLE
I tried your code on STM32F103C8

### ISSUE THREAD

**Issue by nopnop2002** [seeers/CAN-Bus-Arduino_Core_STM32#1]
I tried your code on STM32F103C8 but it didn't work.

My environment:
Arduino_Core_STM32 1.8,0

Pin Connection:
```
STM32F103  MCP2551
PB9      --TXD
GND      --VSS
5V       --VDD
PB8      --RXD
GND      --RS
           CNAH     -----  To Arduino DUE
           CANL     -----  TO Arduino DUE
```

Arduino-DUE and Arduino-UNO can communicate properly.
Can you any advice??

**Comment by seeers** [comment]
Should actually work. So far I have only tested it with a usbtin. https://www.fischl.de/usbtin/

**Comment by nopnop2002** [comment]
Thank you for your reply.
I also prepare USBTIN.
